//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project109.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_categories
    {
        public int Id { get; set; }
        public string cat_name { get; set; }
    }
}
