//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project109.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int Id { get; set; }
        public string book_Title { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> sold_by { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<int> publishing_year { get; set; }
        public string stock { get; set; }
        public string book_cover { get; set; }
        public string book_softcopy { get; set; }
        public Nullable<System.DateTime> date_insert { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<bool> active { get; set; }
        public string book_language { get; set; }
        public Nullable<int> book_cat { get; set; }
    }
}
