//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project109.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class msaadtestEntities : DbContext
    {
        public msaadtestEntities()
            : base("name=msaadtestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<publishers> publishers { get; set; }
        public virtual DbSet<users_types> users_types { get; set; }
        public virtual DbSet<UsersAdmins> UsersAdmins { get; set; }
        public virtual DbSet<view_books> view_books { get; set; }
        public virtual DbSet<view_orders> view_orders { get; set; }
        public virtual DbSet<view_users> view_users { get; set; }
        public virtual DbSet<books_categories> books_categories { get; set; }
    }
}
