//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project109.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAdmins
    {
        public long Id { get; set; }
        public string RealName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> date_insert { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    }
}
